openapi: 3.0.3
info:
  title: Locale API
  contact: {}
  version: '1.0'
servers:
  - url: https://locale-api.cyclic.app/api/v1
    variables: {}
paths:
  /user/register:
    post:
      tags:
        - User
      summary: Register User
      operationId: RegisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
            example:
              username: Butcher27
              email: itch56@gmail.com
              password: Mmjok784@3
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    parameters: []
  /user/login:
    post:
      tags:
        - User
      summary: Login User
      operationId: LoginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: itch56@gmail.com
              password: Mmjok784@3
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    parameters: []
  /locale/search:
    get:
      tags:
        - Auth
      summary: Get Locations
      operationId: GetLocations
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    parameters: []
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - username
        - email
        - password
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: User
    description: ''
  - name: Auth
    description: ''
